DEBUG 2021-03-15 16:16:34.299 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-03-15 16:16:34.300 UTC: 	 Running on: Linux lxplus712.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-15 16:16:34.300 UTC: 	 Executing command: 'submit'
DEBUG 2021-03-15 16:16:34.300 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-03-15 16:16:34.301 UTC: 	 Will use CRAB configuration file DoubleMuon_Run2018A_cfg.py
DEBUG 2021-03-15 16:16:34.301 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-03-15 16:16:34.305 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-03-15 16:16:34.306 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/crab/crab2018/crab_DoubleMuon_Run2018A_2018' already exists 
Please change the requestName in the config file
ERROR 2021-03-15 16:16:34.306 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/crab/crab2018/crab_DoubleMuon_Run2018A_2018' already exists 
Please change the requestName in the config file
INFO 2021-03-15 16:16:34.309 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/crab/crab.log
